# --cluster-cidr=10.244.0.0/16
# --service-cluster-ip-range=10.96.0.0/12

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: openvpn-cfg
  namespace: kube-system
data:
  openvpn.tmpl: |
    server ${OVPN_NETWORK_ROUTE}
    topology subnet
    verb ${OVPN_VERB}

    # Filled by Secrets object. Use generic names
    key ${EASYRSA_PKI}/private.key
    ca ${EASYRSA_PKI}/ca.crt
    cert ${EASYRSA_PKI}/certificate.crt

    dh ${EASYRSA_PKI}/dh.pem
    tls-auth ${EASYRSA_PKI}/ta.key

    # ecdh-curve secp256k1

    key-direction 0
    keepalive 10 60
    persist-key
    persist-tun
    push "block-outside-dns"

    proto ${OVPN_PROTO}
    cipher ${OVPN_CIPHER}
    tls-cipher ${OVPN_TLS_CIPHER}

    # Rely on scheduler to do port mapping, internally always 1194
    port 1194
    dev tun0

    user nobody
    group nogroup

    push "dhcp-option DOMAIN ${OVPN_K8S_DOMAIN}"
    push "dhcp-option DNS ${OVPN_K8S_DNS}"

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: openvpn-crl
  namespace: kube-system
data:
  crl.pem: |
  -----BEGIN X509 CRL-----
  MIIBsTCBmgIBATANBgkqhkiG9w0BAQsFADAZMRcwFQYDVQQDDA5tMi5hZ2Fmb25v
  di5tZRcNMjEwNDI5MjAxNTMxWhcNMzEwMzA4MjAxNTMxWqBNMEswSQYDVR0jBEIw
  QIAUqT1K+lHFjNlkgNK1nrtpxcbrd/ihHaQbMBkxFzAVBgNVBAMMDm0yLmFnYWZv
  bm92Lm1lggkAkI6hdeVPPJswDQYJKoZIhvcNAQELBQADggEBAEcrtGlSjyf4OM4f
  QydgZxl4+fPmPYmPdI1f30cZ1TDBnTK8hnovFM8vD7Hq9OFRZuJXthp+4q+QYEMK
  3DDWETbTTrBVcBGkh0Wlo0e/lPH8QzAfCxR2EEde0xAX/+5K6ymK9/cfG1SV0qrv
  CYTOC3awd2uq7gE7/zWoXHt5ye2Xf8ZcxT8YIm8DakGc370YljJ1i4oZeo+POSi9
  ze/F4ckJxukVyCF6TFrNVOLjNAxLDgvke9hbpbTdDj9HqkcpJa+3x7j+0OEjKfq+
  5sZUa2wMKkKirnUJZ/zbKuGhv1apA66MiToXTz1kDS/Y3cradFiH/SwZ0Up7yLxp
  k0Abo8I=
  -----END X509 CRL-----

---
apiVersion: v1
kind: Secret
metadata:
  name: openvpn-pki
  namespace: kube-system
type: Opaque
data:
  private.key: >-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQy8vYjVJb0g5cWd2ZDIKcytJS0Q3WGlwL1NvNEMwdVBEYW5IMTRjUUFVazZEUmlPWkhiK2NCcTdZd1FZTDZ0SlU3Z0t5Z2JCb1JrcjloagpMQlRRSFA3azVNdGNacHQ0WFdKVU1PTGQvNmJrNWlsaGdpbzlpdk5WOEN1V29LR3ZrVzJIZXZpMmxwVG1Hc3Y3CnhyNGkrNVdxdjgraGhtVWZhenJ1MnEyalg3UE13azNXd09YRXRDUDExTEVLWlY4VWl6ZUxRLzJMQnJWYVc1a3IKSDVmVnZMV0pnWHhDZTAyd1FDOThLSUNHL1Y5eTBPYnd1Nlk5NVc1MUM3cXdsQkR4TGxoNkpMWjNmUzJNaVI4MApYRTBIbjZtOXZwU1ZrYUFqdDFtUzNxYzNRSGJxa3FhTzNMcFZUUkFISldmbmZSOE5jcXFFVXBUYW5FTEdiNWFGCmxMT0Vhbm1OQWdNQkFBRUNnZ0VCQUwxSFNTaks2ck0wYVFvaTcrOWhhNzBJUHNHYk9ZL0NsMU1PTHJjRk9zMFgKREVYbVlmR1ArVzZ4d1F1SWhaT29HMm9Qd2h0YXduMk5pM1RDU2NhZlA0Q2tQQVZkdDFya0hnUElxbkdaRUkzTQpoL0YwNVhZRkhqK1VaelM2S28wdmY5ODRraWxZclhWcDU3N1NRak8wK3VuNjdwVmRMU2Jialo5Y0FpSDJRUW5VCnNqNStINmYwU0JDUXRteDV1UDhCVTRqWlRFYmpYYmpvdnNBMElKM1ZWeExOQllrak1IZjl2K1NPa3AvQzFGNTgKZUVjUXJMbGZQQk5pTlVRektKMGpoT21wMGFPMjlRR0dmeEdXQjA4UEVDMXBHNFcyYXE4UHBzNzk5czc3bkZ3YQpRTnhtL3pQdnY4NkF3YWU5MUttR01tZnNPNHhPWmNWRXE4TFI4MyttVVlFQ2dZRUE5dnVnTmthRjJaazF2Y01aCkdCZ01obEorZ2VuNmM2ZGVrR29GazQyR3JhN3F0Y2NKRFNyUnY3NmZ1TzZqQnpySTlxT21PY3RQZXVIMzBiVmMKc2h5MGFGTHVjb1liczNXM3MwNW9tR1BYL25lb2Z1ajlTWm80b3NUemZZSDJBTHBpMXp4end5aFFVMWxvclZ1bQovM3FodGZJWGdWSzN0VEYyc1Z5NC9wNE5HR0VDZ1lFQXh3QW1GZHIzbmNvNU1xRURTOUExV2ExRm1XeUV6Ni9BCjRMdUxEZVgvTXRLMU5CZFZ6Qm1Xak13NFlPYjE3RHlMYUpNaGtvNDc1TGpLNW9id3p3NndJL012akY2TFVZM2YKRjdPazFMKzJPUCswZmgwaEVxZTlxbVZ3NGhPRWdwZEp1d1JqTUxQcVVXSEt3UkRsYTNDV2F5R0FISURGNGE0dApoMDlDd09zeEFLMENnWUJUdURHemxDNDA5Mmt2SE4zNXU5VXJCdldaQmYzK2pDSlM0NDFtV2Rmb01kMmZwb3NiCjZvTFU4MEhqQndrK0h5QVY4cDBiQkI2NThiVDJZZnE4NlZ3QjdQS2s0VzZzWTEvVXFPUnRtNUtRMEhET0xCNEgKZi81b3RrZ3ZLQW1DYjZ1bmQvZHBsTlc5bXhZUGhYelRKdmQvM0VNNWRCZVBsT2U5OFVkSUQ3MHlvUUtCZ1FDbgpDZTN1SEg0Sytlc25IMVpuOWQ1Q1p4cHIzVlppQ3JJSk1nTlg2RDVkaDliSVllb0h4MWJDMnMxY01hSXQ2T2hRCklHaG0zM05RMnZpZHBwbE9CSk0vcWVxNGxjZTE3ak5jYnRPbUxVSWsrQ2FtVVljb1pKcmxBLzlNRlh2K0xrV2EKY09WZHhUZWpsa1dkNTdQYmlvY0laL2RrZFlja2w1THA2Rk10SW41Z2hRS0JnUUREYWFFTHIva28xNEdXY3R0eQpxVC9qbXZNV1p5VXBRR0xsQ3lyaDVmend5aS9ScEk5VEtwSWRhTWVxK3p3Z0JQWmZxS0J4TkU2RFVOaWs1MGErCjUva0VTcjJab0g2dnV2TmZFdWFxUXJsbGtQMS9ycWt0aWpRaGwyZGwrU0xPRmd6bnBaS2lSVnp1dFp6QkZ5ZW8KUm5oaUptN2xHdUdBaHd1WTJGU2hJNFNFU2c9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  ca.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQakNDQWlhZ0F3SUJBZ0lKQUpDT29YWGxUenliTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURtMHlMbUZuWVdadmJtOTJMbTFsTUI0WERUSXhNRFF5T1RJd01UTXdPRm9YRFRNeE1EUXlOekl3TVRNdwpPRm93R1RFWE1CVUdBMVVFQXd3T2JUSXVZV2RoWm05dWIzWXViV1V3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUURZa3o4L3h6WnZJOFJsa3dJYTJjT1pmZUVzN1FqTUdKZzBCUFFsdjc1RGFLTWcKOENSMnVReHZSekdGaWsrTmRuVFNwL3pzYmhYT3VaeGRYL2h0eXdQWUxMdTUvSUZvTENHZzh4WXhqeEVOb01TWgpDQ3JvcERnWFVIaFhBNWIyYktLOWZWRkRzMzd2MytJN0hJV0p3bVh0YTl5R1ZBa0IySmlucTZWRVNaSDQvV2s3CjJqRGxKa1h3Zno3T05uZGd2ZGtXMUNNSzQ4cnJRcUV1Ry8zQUU1RmljdEJ3UCtqNXBPYTlnbGJHYVRtY0QxWEQKQk1KaFNpUXZpbzZzd2YvMzRtVmpRUFNvMVRxb0dGdktZS0FETEcySWltQ21pRlZpUCtOVHR0bW1MZzQwK1cwTQprQksrbFdCL21GbDhBd0pwSW9HY3VwR1ErSkticFoxQm1ROVpDTGdOQWdNQkFBR2pnWWd3Z1lVd0hRWURWUjBPCkJCWUVGS2s5U3ZwUnhZelpaSURTdFo2N2FjWEc2M2Y0TUVrR0ExVWRJd1JDTUVDQUZLazlTdnBSeFl6WlpJRFMKdFo2N2FjWEc2M2Y0b1Iya0d6QVpNUmN3RlFZRFZRUUREQTV0TWk1aFoyRm1iMjV2ZGk1dFpZSUpBSkNPb1hYbApUenliTUF3R0ExVWRFd1FGTUFNQkFmOHdDd1lEVlIwUEJBUURBZ0VHTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQXE1S2JFaVR1SVlpeHN3Mmt3cEtlbWpUQUVmcHZ1Zkg4QVN6UGRHVWdMUlp1czNYU2FHSWl4QXExSGV6ZUsKR0ptcCttQVpxVlJxM2dXc2RLTWEzdFJsSjhwZytCK3pWVmlFemVRb2Y3Y3FMTlBObWdjNkk1LzBFUUlyb2crWgpOdlZCUWFZcWR4NFI2N3NETytsMEVzMlA5ZjZBbUU2MmtiR0tvaG5Id0VEbkJSbnVNNHJ3MWY0NXIyRnFlZDJGCnBUeU1FZnE0OGFZMUliR2R3M2tIN2xZWCt1czVoUU1oZml4QkdjbVY4bXVBWkhuaWJ6bXNMUS9UakNodEUvT1YKditSYjhiTnBoN2tSbmRVaDIzNWhHZ3F6dWU3RkVxQWVyaUFxTHRLS1BrbXNLbGJOQWZPemhtejR0dzlwa3ViTgowS0pGWGxQdGNKci8wa1MvMk80Rkp4Yk8KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  certificate.crt: >-
    Q2VydGlmaWNhdGU6CiAgICBEYXRhOgogICAgICAgIFZlcnNpb246IDMgKDB4MikKICAgICAgICBTZXJpYWwgTnVtYmVyOgogICAgICAgICAgICAxMzphMzo1ZjpiMzpmYjpmNjpmMTowMDoxNjpmYjozZDplNDpjNDoxOToxODo5MwogICAgU2lnbmF0dXJlIEFsZ29yaXRobTogc2hhMjU2V2l0aFJTQUVuY3J5cHRpb24KICAgICAgICBJc3N1ZXI6IENOPW0yLmFnYWZvbm92Lm1lCiAgICAgICAgVmFsaWRpdHkKICAgICAgICAgICAgTm90IEJlZm9yZTogQXByIDI5IDIwOjEzOjM1IDIwMjEgR01UCiAgICAgICAgICAgIE5vdCBBZnRlciA6IEFwciAyNyAyMDoxMzozNSAyMDMxIEdNVAogICAgICAgIFN1YmplY3Q6IENOPW0yLmFnYWZvbm92Lm1lCiAgICAgICAgU3ViamVjdCBQdWJsaWMgS2V5IEluZm86CiAgICAgICAgICAgIFB1YmxpYyBLZXkgQWxnb3JpdGhtOiByc2FFbmNyeXB0aW9uCiAgICAgICAgICAgICAgICBQdWJsaWMtS2V5OiAoMjA0OCBiaXQpCiAgICAgICAgICAgICAgICBNb2R1bHVzOgogICAgICAgICAgICAgICAgICAgIDAwOmJmOmZkOmJlOjQ4OmEwOjdmOjZhOjgyOmY3Ojc2OmIzOmUyOjBhOjBmOgogICAgICAgICAgICAgICAgICAgIGI1OmUyOmE3OmY0OmE4OmUwOjJkOjJlOjNjOjM2OmE3OjFmOjVlOjFjOjQwOgogICAgICAgICAgICAgICAgICAgIDA1OjI0OmU4OjM0OjYyOjM5OjkxOmRiOmY5OmMwOjZhOmVkOjhjOjEwOjYwOgogICAgICAgICAgICAgICAgICAgIGJlOmFkOjI1OjRlOmUwOjJiOjI4OjFiOjA2Ojg0OjY0OmFmOmQ4OjYzOjJjOgogICAgICAgICAgICAgICAgICAgIDE0OmQwOjFjOmZlOmU0OmU0OmNiOjVjOjY2OjliOjc4OjVkOjYyOjU0OjMwOgogICAgICAgICAgICAgICAgICAgIGUyOmRkOmZmOmE2OmU0OmU2OjI5OjYxOjgyOjJhOjNkOjhhOmYzOjU1OmYwOgogICAgICAgICAgICAgICAgICAgIDJiOjk2OmEwOmExOmFmOjkxOjZkOjg3OjdhOmY4OmI2Ojk2Ojk0OmU2OjFhOgogICAgICAgICAgICAgICAgICAgIGNiOmZiOmM2OmJlOjIyOmZiOjk1OmFhOmJmOmNmOmExOjg2OjY1OjFmOjZiOgogICAgICAgICAgICAgICAgICAgIDNhOmVlOmRhOmFkOmEzOjVmOmIzOmNjOmMyOjRkOmQ2OmMwOmU1OmM0OmI0OgogICAgICAgICAgICAgICAgICAgIDIzOmY1OmQ0OmIxOjBhOjY1OjVmOjE0OjhiOjM3OjhiOjQzOmZkOjhiOjA2OgogICAgICAgICAgICAgICAgICAgIGI1OjVhOjViOjk5OjJiOjFmOjk3OmQ1OmJjOmI1Ojg5OjgxOjdjOjQyOjdiOgogICAgICAgICAgICAgICAgICAgIDRkOmIwOjQwOjJmOjdjOjI4OjgwOjg2OmZkOjVmOjcyOmQwOmU2OmYwOmJiOgogICAgICAgICAgICAgICAgICAgIGE2OjNkOmU1OjZlOjc1OjBiOmJhOmIwOjk0OjEwOmYxOjJlOjU4OjdhOjI0OgogICAgICAgICAgICAgICAgICAgIGI2Ojc3OjdkOjJkOjhjOjg5OjFmOjM0OjVjOjRkOjA3OjlmOmE5OmJkOmJlOgogICAgICAgICAgICAgICAgICAgIDk0Ojk1OjkxOmEwOjIzOmI3OjU5OjkyOmRlOmE3OjM3OjQwOjc2OmVhOjkyOgogICAgICAgICAgICAgICAgICAgIGE2OjhlOmRjOmJhOjU1OjRkOjEwOjA3OjI1OjY3OmU3OjdkOjFmOjBkOjcyOgogICAgICAgICAgICAgICAgICAgIGFhOjg0OjUyOjk0OmRhOjljOjQyOmM2OjZmOjk2Ojg1Ojk0OmIzOjg0OjZhOgogICAgICAgICAgICAgICAgICAgIDc5OjhkCiAgICAgICAgICAgICAgICBFeHBvbmVudDogNjU1MzcgKDB4MTAwMDEpCiAgICAgICAgWDUwOXYzIGV4dGVuc2lvbnM6CiAgICAgICAgICAgIFg1MDl2MyBCYXNpYyBDb25zdHJhaW50czogCiAgICAgICAgICAgICAgICBDQTpGQUxTRQogICAgICAgICAgICBYNTA5djMgU3ViamVjdCBLZXkgSWRlbnRpZmllcjogCiAgICAgICAgICAgICAgICA2MzowQjo1QTpGQTpDMTpEQjozQTo4NTo1Njo3RTpBRjoxODo1RjpCMjo1RDpCMzo5Qzo3NDo2Mjo5MAogICAgICAgICAgICBYNTA5djMgQXV0aG9yaXR5IEtleSBJZGVudGlmaWVyOiAKICAgICAgICAgICAgICAgIGtleWlkOkE5OjNEOjRBOkZBOjUxOkM1OjhDOkQ5OjY0OjgwOkQyOkI1OjlFOkJCOjY5OkM1OkM2OkVCOjc3OkY4CiAgICAgICAgICAgICAgICBEaXJOYW1lOi9DTj1tMi5hZ2Fmb25vdi5tZQogICAgICAgICAgICAgICAgc2VyaWFsOjkwOjhFOkExOjc1OkU1OjRGOjNDOjlCCgogICAgICAgICAgICBYNTA5djMgRXh0ZW5kZWQgS2V5IFVzYWdlOiAKICAgICAgICAgICAgICAgIFRMUyBXZWIgU2VydmVyIEF1dGhlbnRpY2F0aW9uCiAgICAgICAgICAgIFg1MDl2MyBLZXkgVXNhZ2U6IAogICAgICAgICAgICAgICAgRGlnaXRhbCBTaWduYXR1cmUsIEtleSBFbmNpcGhlcm1lbnQKICAgICAgICAgICAgWDUwOXYzIFN1YmplY3QgQWx0ZXJuYXRpdmUgTmFtZTogCiAgICAgICAgICAgICAgICBETlM6bTIuYWdhZm9ub3YubWUKICAgIFNpZ25hdHVyZSBBbGdvcml0aG06IHNoYTI1NldpdGhSU0FFbmNyeXB0aW9uCiAgICAgICAgIGFhOjEzOmJjOmRiOjdkOjFlOjQxOjIxOmUyOjVjOmEyOmMzOjE4OmY3OmIyOmE2OmFjOjQxOgogICAgICAgICA3YTpjYTo3NDo4MzozNjplNzo4NDpkOTplZjpmZjo4YjoyZjpkODoyODo0OTplZDozODo3NToKICAgICAgICAgZmY6YmE6NDA6MTY6OWI6ZjA6ZGU6Y2E6Yzk6Yjc6N2E6ODk6ZWY6ZGQ6YmY6N2Y6MDI6OTk6CiAgICAgICAgIDdjOmJmOjhhOjY4OmI4OmQ1OjQ1OjU5OjM2OmVkOmRhOjRhOjI0OmU3OmJlOjI5OjNiOmQxOgogICAgICAgICAwYTpiNjozZTozZDo4MDpmOTpmNzpmYTo4NjpmYjowMTpkODo0MjpmYjo0Yjo2YzozZDoyZDoKICAgICAgICAgMzA6N2M6NmM6Yzk6Mjk6ZmQ6YWI6ODI6MTc6MmE6ZTc6Y2E6ZWE6MDA6NGY6MzA6ODU6YTE6CiAgICAgICAgIDdhOjE1OjkxOjA0OjgwOjEyOjM4OmRkOmI3OjU2OjBmOjdjOjA3OmM2OmIzOjUxOjU2OmE0OgogICAgICAgICAzYzo4NDplMjplZTpjNzpiMToyNjo4ZjpiZjo3MDo2Njo0ZjpmNTplOTo4YzozNjo2NDozYjoKICAgICAgICAgZGE6YjY6YWE6NDc6NjE6Nzc6ZmQ6ZDQ6NGQ6MzE6ZTE6NGM6OTk6MWE6Yzk6ZmE6YjU6ZWY6CiAgICAgICAgIDM1OjUxOjQ5Ojg1OmE1OmNkOmI0OjZhOmY2OmFjOjNhOjU2OjdiOmUwOjc0OjE5OjA0OjgyOgogICAgICAgICA0YjphYTo5YjplYjoxNTo5YzpkYTpmYjowMDo3YzoyZjo5YTo0NDoyOTo2MDoyYjowMTo4YjoKICAgICAgICAgZWI6NGQ6YjE6MzE6YzU6NDk6ZWI6NTI6ZGU6ZDA6NGM6NWQ6N2M6YTI6ODE6OWE6NTQ6OTg6CiAgICAgICAgIGMzOjFiOjllOjQ1OjBhOjI1OjNjOmY4OmY3Ojk0OmZiOjVmOjdlOjQwOjYzOjk0OjZiOjY4OgogICAgICAgICBmOTplYjo5Yjo4MzpjNjo2MDpkOTo1YzoyZjpiYzo1ZTo4OTpmOTpiMTo2Yjo3MDozZjo3NzoKICAgICAgICAgOGM6MzQ6ZWE6YjUKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjakNDQWxxZ0F3SUJBZ0lRRTZOZnMvdjI4UUFXK3oza3hCa1lrekFOQmdrcWhraUc5dzBCQVFzRkFEQVoKTVJjd0ZRWURWUVFEREE1dE1pNWhaMkZtYjI1dmRpNXRaVEFlRncweU1UQTBNamt5TURFek16VmFGdzB6TVRBMApNamN5TURFek16VmFNQmt4RnpBVkJnTlZCQU1NRG0weUxtRm5ZV1p2Ym05MkxtMWxNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF2LzIrU0tCL2FvTDNkclBpQ2crMTRxZjBxT0F0TGp3MnB4OWUKSEVBRkpPZzBZam1SMi9uQWF1Mk1FR0MrclNWTzRDc29Hd2FFWksvWVl5d1UwQnorNU9UTFhHYWJlRjFpVkREaQozZittNU9ZcFlZSXFQWXJ6VmZBcmxxQ2hyNUZ0aDNyNHRwYVU1aHJMKzhhK0l2dVZxci9Qb1labEgyczY3dHF0Cm8xK3p6TUpOMXNEbHhMUWo5ZFN4Q21WZkZJczNpMFA5aXdhMVdsdVpLeCtYMWJ5MWlZRjhRbnROc0VBdmZDaUEKaHYxZmN0RG04THVtUGVWdWRRdTZzSlFROFM1WWVpUzJkMzB0aklrZk5GeE5CNStwdmI2VWxaR2dJN2Raa3Q2bgpOMEIyNnBLbWp0eTZWVTBRQnlWbjUzMGZEWEtxaEZLVTJweEN4bStXaFpTemhHcDVqUUlEQVFBQm80RzFNSUd5Ck1Ba0dBMVVkRXdRQ01BQXdIUVlEVlIwT0JCWUVGR01MV3ZyQjJ6cUZWbjZ2R0YreVhiT2NkR0tRTUVrR0ExVWQKSXdSQ01FQ0FGS2s5U3ZwUnhZelpaSURTdFo2N2FjWEc2M2Y0b1Iya0d6QVpNUmN3RlFZRFZRUUREQTV0TWk1aApaMkZtYjI1dmRpNXRaWUlKQUpDT29YWGxUenliTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQk1Bc0dBMVVkCkR3UUVBd0lGb0RBWkJnTlZIUkVFRWpBUWdnNXRNaTVoWjJGbWIyNXZkaTV0WlRBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFxaE84MjMwZVFTSGlYS0xER1BleXBxeEJlc3AwZ3pibmhObnYvNHN2MkNoSjdUaDEvN3BBRnB2dwozc3JKdDNxSjc5Mi9md0taZkwrS2FMalZSVmsyN2RwS0pPZStLVHZSQ3JZK1BZRDU5L3FHK3dIWVF2dExiRDB0Ck1IeHN5U245cTRJWEt1Zks2Z0JQTUlXaGVoV1JCSUFTT04yM1ZnOThCOGF6VVZha1BJVGk3c2V4Sm8rL2NHWlAKOWVtTU5tUTcycmFxUjJGMy9kUk5NZUZNbVJySityWHZOVkZKaGFYTnRHcjJyRHBXZStCMEdRU0NTNnFiNnhXYwoydnNBZkMrYVJDbGdLd0dMNjAyeE1jVko2MUxlMEV4ZGZLS0JtbFNZd3h1ZVJRb2xQUGozbFB0ZmZrQmpsR3RvCitldWJnOFpnMlZ3dnZGNkorYkZyY0Q5M2pEVHF0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  dh.pem: >-
    LS0tLS1CRUdJTiBESCBQQVJBTUVURVJTLS0tLS0KTUlJQkNBS0NBUUVBeTBueTg2N1Zoa2k3dG1yUmZqc1lncVpEZzZWOUVDWUJ5dGwwUGlwZi9CS2o1aUc4V1RkNApBYmdUbTkrRGhtMjlwMUw2OTFPMzFwTlg5djlha1RkZHZqeVlmR1pKME42a0FRZWo0ODk4NnUwZ1VqUlpESkxPClMzakpRMFRCYWp1alEybU4wdE02b2l6RzNxWkpCTkxkL3VaYUZpZ2tYcUE3c214YWNXOVdNaSthcW51UU81LzMKZWhxbVpsRmovTTYrbEFhaURmbTk0VDAzbUhOSFRwUU5yTmo1WUN3NHZjejgvSHU3azByaGd1WDJBODBaaDY3ZQpKTVZEYlhZWUo1Si80OU4wWXl6TzNJWHBvTTkxMzB6ZitGZExPeitqYnZGOTBIaklXc1FxZ2NSNXpsbWJHQ2RMCnRWSGdFenFIc2NNcm9RcC9Pd1UrcUhjRERiQkxIVEZVUXdJQkFnPT0KLS0tLS1FTkQgREggUEFSQU1FVEVSUy0tLS0tCg==
  ta.key: >-
    IwojIDIwNDggYml0IE9wZW5WUE4gc3RhdGljIGtleQojCi0tLS0tQkVHSU4gT3BlblZQTiBTdGF0aWMga2V5IFYxLS0tLS0KNzQ0MjE3OGRlMGQzZTZjNmM2NmFkODM5M2E0YWRiYWMKMmI2YmU0MDMyMTUwNDNlODkxZDlhNDJiNjZhNDU3ZWUKOTk0ZDg1ZGJkMTMzMDIzOTBhMzBkY2EwZTM3NmM5ZDQKN2NiZjQ0MzlkMjYyMWUzNjAwZTczMDY2MDBkOWU0MzYKYjcyN2JlNDY3MmMxYzkzZWFjYWVhZjgxMTUzZGMzYTUKNzA5MWI4Y2Y0MmRmMWRlMjJjNTFhZTA4M2NkNGI4OWQKZWM5NmViYzkzMDg4NjA0YjZkMjE4MjA3NzYxMzVlZjQKY2FhMTRlYWM4ZWYxNGNhMjI1MWVhZjAyZmQ0MTRlOTIKYzJjM2I4NzhhMGYwM2JiN2NlZTUzYjM5MThjMjQ1ZDYKYzA1MGM3NTM2ZjU2NzY1MzJhMWEwODI0ZmYxMWY4NDkKMTNiOTE3MjI3Nzc5YTZlNTJkZDRiY2NmZTVhZjcwZmIKNzI0YjVjM2EzN2EzZTE3OTc0NzJiZGU1NzgzNjQ2ODUKNGM1N2JiYWE3YjEwMGI0MTkyNzFkYWYwYjg5YTQ2MjMKZTk1YjExZDk2MjU1MmU2YjdjYzllMzMyOGE1N2QwMTQKYTExMGUzNTliMDUwZmFlZGRlMTBhZjJjYjdmODkyN2IKMGVhZmFjYTU2MGFiMDhmMTM1YmE5ZWViNWVhZmVhYTIKLS0tLS1FTkQgT3BlblZQTiBTdGF0aWMga2V5IFYxLS0tLS0K


#  private.key: "$($base64 pki/private/${OVPN_CN}.key)"
#  ca.crt: "$($base64 pki/ca.crt)"
#  certificate.crt: "$($base64 pki/issued/${OVPN_CN}.crt)"
#  dh.pem: "$($base64 pki/dh.pem)"
#  ta.key: "$($base64 pki/ta.key)"

# server
# docker run --user=$(id -u) -e OVPN_SERVER_URL=tcp://vpn.my.fqdn:1194 -v $PWD:/etc/openvpn:z -ti ptlange/openvpn ovpn_initpki
# docker run --user=$(id -u) -e EASYRSA_CRL_DAYS=180 -v $PWD:/etc/openvpn:z -ti ptlange/openvpn easyrsa gen-crl

# client
# docker run --user=$(id -u) -v $PWD:/etc/openvpn:z -ti ptlange/openvpn easyrsa build-client-full CLIENTNAME nopass
# docker run --user=$(id -u) -e OVPN_SERVER_URL=tcp://vpn.my.fqdn:1194 -v $PWD:/etc/openvpn:z --rm ptlange/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn

# openvpn --config /etc/openvpn/openvpn.conf --push route 10.96.0.0 255.240.0.0 --push route 10.244.0.0 255.255.0.0 --crl-verify /etc/openvpn/crl/crl.pem --status /etc/openvpn/status/server.status --status-version 2

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openvpn-settings
  namespace: kube-system
data:
  servicecidr: "10.96.0.0/12"
  podcidr: "10.244.0.0/16"
  serverurl: "tcp://host:1194"
  domain: "host"
  statusfile: "/etc/openvpn/status/server.status"

---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  labels:
    openvpn: host
  name: openvpn
spec:
  type: NodePort
  ports:
    - port: 1194
      protocol: TCP
      targetPort: 1194
  selector:
    openvpn: host

#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: openvpn-ccd
#  namespace: kube-system
#data:
#  example: "ifconfig-push 10.140.0.5 255.255.255.0"
#
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: openvpn-portmapping
#  namespace: kube-system
#data:
#  20080: "example:80"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openvpn
  namespace: kube-system
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      openvpn: host
  template:
    metadata:
      labels:
        openvpn: host
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9176"
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: openvpn
          image: quay.io/plange/openvpn:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - mountPath: /etc/openvpn/templates/
              name: openvpn-cfg
            - mountPath: /etc/openvpn/pki
              name: openvpn-pki
            - mountPath: /etc/openvpn/crl
              name: openvpn-crl
#            - mountPath: /etc/openvpn/ccd
#              name: openvpn-ccd
#            - mountPath: /etc/openvpn/portmapping
#              name: openvpn-portmapping
            - mountPath: /etc/openvpn/status
              name: openvpn-status
          ports:
            - name: openvpn
              containerPort: 1194
          env:
            - name: PODIPADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OVPN_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: openvpn-settings
                  key: serverurl
            - name: OVPN_K8S_SERVICE_NETWORK
              valueFrom:
                configMapKeyRef:
                  name: openvpn-settings
                  key: servicecidr
            - name: OVPN_K8S_POD_NETWORK
              valueFrom:
                configMapKeyRef:
                  name: openvpn-settings
                  key: podcidr
            - name: OVPN_K8S_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: openvpn-settings
                  key: domain
            - name: OVPN_STATUS
              valueFrom:
                configMapKeyRef:
                  name: openvpn-settings
                  key: statusfile
        - name: metrics
          image: quay.io/plange/openvpn_exporter:latest
          ports:
            - name: openvpn
              containerPort: 9176
          volumeMounts:
            - mountPath: /etc/openvpn_exporter/
              name: openvpn-status
      volumes:
        - name: openvpn-cfg
          configMap:
            defaultMode: 0555
            name: openvpn-cfg
        - name: openvpn-pki
          secret:
            secretName: openvpn-pki
            defaultMode: 0400
#        - name: openvpn-ccd
#          configMap:
#            name: openvpn-ccd
        - name: openvpn-crl
          configMap:
            defaultMode: 0555
            name: openvpn-crl
#        - name: openvpn-portmapping
#          configMap:
#            name: openvpn-portmapping
        - name: openvpn-status
          emptyDir: {}
