kind: Deployment
apiVersion: apps/v1
metadata:
  name: zk-manager-deployment
  namespace: zookeeper
  labels:
    app: zookeeper-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zookeeper-manager
    spec:
      containers:
        - name: zookeeper-manager
          image: 'elkozmon/zoonavigator:latest'
          ports:
            - containerPort: 9000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: zookeeper-manager-service
  namespace: zookeeper
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: zookeeper-manager
  type: ClusterIP
  sessionAffinity: None

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-manager
  namespace: zookeeper
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: zookeeper-secret-basic
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
    - hosts:
        - host
      secretName: zookeeper-secret-tls
  rules:
    - host: host
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: zookeeper-manager-service
              servicePort: 9090

# docker run -d -e HTTP_PORT=9000 --name zn --restart unless-stopped --network=host elkozmon/zoonavigator:latest
# internal service with port forwarding

---
kind: Service
apiVersion: v1
metadata:
  name: zk-manager-ex
  namespace: zookeeper
  labels:
    app: zookeeper-manager
spec:
  ports:
    - name: client
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: zookeeper-manager
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster