apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      name: superset
      labels:
        app: superset
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - host
      containers:
        - name: superset
#          image: apache/superset:master
          image: igoradm90/superset:0.0.1
          ports:
            - name: superset
              containerPort: 8088
          resources:
            requests:
              memory: 200Mi
              cpu: "100m"

#  superset fab create-admin \
#  --username name \
#  --firstname fn \
#  --lastname ln \
#  --email email \
#  --password pwd

# superset db upgrade

# superset init

---
kind: Service
apiVersion: v1
metadata:
  name: superset-dashboard
  namespace: apache
  labels:
    k8s-app: superset-dashboard
spec:
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  selector:
    app: superset
  type: ClusterIP
  sessionAffinity: None

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: superset-dashboard
  namespace: apache
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: apache-secret-basic
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - host
      secretName: apache-secret-tls
  rules:
    - host: host
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: superset-dashboard
              servicePort: 8088

